name: Simple Build Test

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pyqt5
        pip install pyinstaller
    - name: Simple build test
      run: |
        echo "Testing basic PyInstaller functionality..."
        pyinstaller --version
        python -c "import PyQt5; print('PyQt5 OK')"
        ls -la
        # 尝试最简单的打包
        pyinstaller --onefile PLNet4.py || echo "Build failed, but continuing..."
    - name: Upload any results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          dist/
          build/
        if-no-files-found: ignore